# Generated by Django 5.0.1 on 2024-01-07 20:08

import django.db.models.deletion
import file.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to=file.models.get_upload_path)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.directory')),
            ],
        ),
    ]
