# Generated by Django 5.0.1 on 2024-04-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_alter_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
