# Generated by Django 5.0.1 on 2024-04-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0007_recent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalFileSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_size', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
