# Generated by Django 5.0.1 on 2024-05-01 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0008_totalfilesize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='expired_date',
        ),
    ]
