# Generated by Django 5.0.1 on 2025-03-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0011_recent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='C:\\Users\\asus\\Desktop\\Django\\DMS\\uploads'),
        ),
    ]
