# Generated by Django 5.0.1 on 2025-03-05 16:25

import file.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0013_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=file.models.get_upload_path),
        ),
    ]
