# Generated by Django 5.0.1 on 2024-08-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_total_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_size',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
