# Generated by Django 5.0.1 on 2025-03-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_max_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='max_size',
            field=models.PositiveIntegerField(default=104857600),
        ),
    ]
