# Generated by Django 5.0.1 on 2024-01-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='directory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
