# Generated by Django 5.0.1 on 2024-01-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_directory_created_at_directory_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
