# Generated by Django 5.0.1 on 2024-01-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_alter_directory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
