# Generated by Django 5.0.1 on 2024-01-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_directory_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
