# Generated by Django 5.0.1 on 2024-04-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_directory_expired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
