# Generated by Django 5.0.1 on 2024-04-19 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_recent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recent',
            name='files',
        ),
    ]
