# Generated by Django 5.0.1 on 2024-05-01 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_remove_recent_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='expired_date',
        ),
    ]
